blank_issues_enabled: false
contact_links:
  - name: Talk with us on Slack
    url: https://cloud-native.slack.com/archives/C080D3PJMS4
    about: For a fast response, consider asking your question on the CNCF k8sgateway Slack channel.
  - name: K8sGateway Documentation
    url: https://k8sgateway.io/docs/
    about: Check out the K8sGateway docs for helpful information.
