{{- range $entry := (list .Values.gatewayClass .Values.waypointClass) }}
{{- if and $entry $entry.parametersRef.enabled $entry.enabled }}

apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: {{ $entry.parametersRef.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "kgateway.labels" $ | nindent 4 }}
spec:
  kube:
    deployment:
      replicas: {{ $.Values.gateway.proxyDeployment.replicas | default 1 }}
    podTemplate:
    {{- with $entry.parametersRef.podTemplate.extraLabels }}
      extraLabels:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $entry.parametersRef.podTemplate.extraAnnotations }}
      extraAnnotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    envoyContainer:
      image:
        registry: {{ $.Values.gateway.envoyContainer.image.registry | default $.Values.image.registry }}
        repository: {{ $.Values.gateway.envoyContainer.image.repository }}
        tag: {{ $.Values.gateway.envoyContainer.image.tag | default $.Values.image.tag | default $.Chart.Version }}
        pullPolicy: {{ $.Values.image.pullPolicy }}
    service:
      type: {{ $entry.service.type | default "LoadBalancer" }}
    {{- with $entry.service.extraLabels }}
      extraLabels:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $entry.service.extraAnnotations }}
      extraAnnotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $.Values.gateway.stats }}
    stats:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with $.Values.gateway.aiExtension }}
    {{- if .enabled }}
    aiExtension:
      enabled: {{ .enabled }}
      image:
        registry: {{ .image.registry | default $.Values.image.registry }}
        repository: {{ .image.repository }}
        tag: {{ .image.tag | default $.Values.image.tag | default $.Chart.Version }}
        pullPolicy: {{ .image.pullPolicy | default $.Values.image.pullPolicy }}
      {{- if .securityContext }}
      securityContext:
          {{- toYaml .securityContext | nindent 8 }}
      {{- end }}
      {{- if .resources }}
      resources:
          {{- toYaml .resources | nindent 8 }}
      {{- end }}
      {{- if .env }}
      env:
          {{ toYaml .env | nindent 8 }}
      {{- end }}
      {{- if .ports }}
      ports:
          {{ toYaml .ports | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- end }}
---
{{- end }}
{{- end }}
