name: labeler
on:
  pull_request_target:
    types: [opened, edited, reopened]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  labeler:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Sync /kind labels & enforce changelog fields
        uses: kgateway-dev/pr-kind-labeler@f15977b7f894730fbaefcc22e2cd4c7c3d3bfcf2 # untagged main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
